ads_checker/urls.py
from django.urls import path
from . import views

app_name = "ads_checker"
urlpatterns = [
    path("", views.main_page, name="main"),
    path("add_target", views.add_target, name="add_target"),
    path("<int:target_id>/", views.view_target, name="view_target"),
    path("<int:target_id>/poll", views.poll, name="poll"),
    path("<int:target_id>/del", views.delete_target, name="del"),
]

epam_final_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ads_checker.urls")),
]

ads_checker/models.py
from django.db import models


class Target(models.Model):
    title = models.CharField(max_length=200)
    wanted_price = models.FloatField()
    active_ads = models.IntegerField(null=True)
    average_price = models.FloatField(null=True)
    dynamic = models.FloatField(null=True)
    price_difference = models.FloatField(null=True)

    def __str__(self):
        return self.title


class Ad(models.Model):
    target = models.ForeignKey(Target, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    link = models.CharField(max_length=300)
    price = models.CharField(max_length=20)

    def __str__(self):
        return self.title

ads_checker/forms.py
from .models import Target
from django.forms import ModelForm, Textarea, NumberInput


class TargetForm(ModelForm):
    class Meta:
        model = Target
        fields = ["title", "wanted_price"]
        widgets = {
            "title": Textarea(attrs={
                "class": "form-control",
                "type": "text",
                "placeholder": "Title",
                "rows": "5"
            }),
            "wanted_price": NumberInput(attrs={
                "class": "form-control",
                "type": "text",
                "placeholder": "Wanted price"
            })
        }

ads_checker/views.py
from django.shortcuts import render
from django import db
from .forms import TargetForm
from .models import Target, Ad
from .module import AvitoGetTarget


def main_page(request):
    targets = Target.objects.all()
    return render(request, "ads_checker/main_page.html", {"targets": targets})


def poll(request, target_id):       # "POST /1/poll HTTP/1.1" 500 73278
    target = Target.objects.get(id=target_id)   # return [1 object]
    ads = AvitoGetTarget(target).get_info()
    target.active_ads = len(ads[0])
    target.average_price = ads[1]
    target.price_difference = ads[2]
    target.dynamic = ads[3]
    target.save()
    for ad in ads[0]:
        if not Ad.objects.filter(link=ad[1]):
            target_ad = Ad(target=target, title=ad[0], link=ad[1], price=ad[2])    # if item not in db
            target_ad.save()
            db.connections.close_all()
    return main_page(request)


def add_target(request):
    if request.method == "POST":
        form = TargetForm(request.POST)
        form.save()
    form = TargetForm()
    context = {"form": form}
    return render(request, "ads_checker/add_target.html", context)


def view_target(request, target_id):
    target = Target.objects.get(pk=target_id)
    ads = Ad.objects.filter(target_id=target_id)
    context = {"target": target, "ads": ads}
    return render(request, "ads_checker/view_target.html", context)


def delete_target(request, target_id):
    target = Target.objects.filter(pk=target_id)
    target.delete()
    return main_page(request)

ads_checker/templates/ads_checker/add_target.html
{% extends 'ads_checker/frame.html' %}

{% block title %}Add target{% endblock %}

{% block body %}
<form method="post" style="margin:5">
    {% csrf_token %}
    <div>{{form.title}}<br></div>
    {{form.wanted_price}}<br>
    <input type="submit" value="Add target">
</form>
{% endblock %}

ads_checker/templates/ads_checker/frame.html
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
          background: linear-gradient(to left,#f0f000,#00f0f0);
          margin:5px;
          text-align:center;
          width:99%;
          height:100%;
        }
        button, table, th, td {
          border: 1px solid black;
          border-collapse: collapse;
          margin:5px;
        }
        th, td {
          padding: 5px;
          text-align: center;
        }
        .form-control {
            width:40%;
            border: 1px solid #0f0f0f;
            border-radius: .2rem;
            margin:5px;
            padding:5px;
            }

    </style>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<h1>Welcome to the Ads checker</h1>
<button style="padding: 5px;" onclick="/">
    <a href="{% url 'ads_checker:main' %}">Main page</a>
</button><br>

{% block body %}{% endblock %}

{% load static %}

<div style="opacity:0.5;position:absolute;left:60%;z-index: -1">
    <img src="{% static 'ads_checker/jwpfws7fp-c3.png' %}" width="100%">
</div>
</body>

</html>

ads_checker/templates/ads_checker/main_page.html
{% extends 'ads_checker/frame.html' %}

{% block title %}
Main page
{% endblock %}

{% block body %}

<table style="opacity:0.8;position:absolute;left:30%;width:40%;background-color:#40B3DF">
    <tbody>
    <tr>
        <th colspan="7">
            <button>
                <a href="{% url 'ads_checker:add_target' %}">Add new target</a>
            </button>
        </th>
    </tr>
    <tr>
        <th>
            Target name
        </th>
        <th>
            Wanted price
        </th>
        <th>
            Total ads
        </th>
        <th>
            Average price
        </th>
        <th>
            Price difference
        </th>
        <th>
            Price dynamic
        </th>
        <th>

        </th>
    </tr>
    {% for target in targets %}
    <tr>
        <th>
            <a href="{% url 'ads_checker:view_target' target.id %}">{{target.title}}</a>
        </th>
        <th>
            {{target.wanted_price}}
        </th>
        <th>
            {{target.active_ads}}
        </th>
        <th>
            {{target.average_price}}
        </th>
        <th>
            {{target.price_difference}}
        </th>
        <th>
            {{target.dynamic}}
        </th>
        <th>
            <form method="post" action="{% url 'ads_checker:poll' target.id %}" style="margin:5">
                {% csrf_token %}
                <input type="submit" id="{target.id}" value="Update">
            </form>
        </th>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

ads_checker/templates/ads_checker/view_target.html
{% extends 'ads_checker/frame.html' %}

{% block title %}
View target
{% endblock %}

{% block body %}
<table style="opacity:0.8;position:absolute;left:30%;width:40%;background-color:#40B3DF">
    <tbody>
    <tr>
        <th style="border:0px;" colspan="1">
            {{target.title}}
        </th>
        <th style="border:0px;">
            <form method="post" action="{% url 'ads_checker:del' target.id %}" style="margin:5">
                {% csrf_token %}
                <input type="submit" id="{target.id}" value="Delete target">
            </form>
        </th>
    </tr>
    {% for ad in ads %}
    <tr>
        <th>
            <a href="{{ad.link}}">{{ad.title}}</a>
        </th>
        <th>
            {{ad.price}}
        </th>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}